spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/fletraxTracking/protocol/openid-connect/certs
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB